"restaurants" collection and get most popular items functions
carteralbrecht/bitewise pull request #20
Opened 2021-02-16 21:29 UTC by chdero

Added 2 new google cloud functions:
**1** - **menuItemRated**: on menuitem document create, update (or create) the restaurant document that item belongs to, and add it to the list of rated items in reverse sorted order based on avgRating.

**2** - **menuItemUpdated**: on menuitem document update, update the restaurant document that item belongs to, change the avgRating for that menuitem in the restaurant docs list of rated items, and move the item up or down to maintain reverse sorted order based on avgRating.

Added 2 new functions to fsmanager.dart:
**1** - **getTopN(String restId, num numPopular)**: get the top 'nupPopular' rated items from restaurant with id 'restId'. Returns the list of maps, where each map is a menuItemId and the avgRating of that item. If there is less than 'numPopular' items rated for this restaurant, the function will return all the rated items.

**2** - **getTopFive(String restId)**: wrapper for 'getTopN'. This function returns the top five items (or less than 5 if there is less than 5 items rated) for restaurant with id 'restId'. Returns this in the same list of maps format described for 'getTopN'.

----

Tested the cloud functions in browser with firebase emulators:start, and tested the fsmanager functions with the backend test page.

----

Will deploy google cloud functions when this is accepted and merged.

2021-02-16 23:15 UTC, carteralbrecht requested changes

2021-02-16 23:15 UTC, carteralbrecht commented on firebase/functions/index.js
> +                for(index = 0; i < listLen; index++)
is the i here intentional?

2021-02-16 23:15 UTC, carteralbrecht commented on lib/services/fsmanager.dart
> +          List<dynamic> topItems = new List(5);
should this be of variable length (not 5)

2021-02-16 23:44 UTC, chdero commented on lib/services/fsmanager.dart
> +          List<dynamic> topItems = new List(5);
Yes it should be, I forgot to switch it over when I changed it from topFive to topN and made topFive call topN. Will fix it, ty.

2021-02-16 23:44 UTC, chdero commented on firebase/functions/index.js
> +                for(index = 0; i < listLen; index++)
oops no. It still works cause of the break statement in the for loop, but ill fix it.

2021-02-17 01:15 UTC, carteralbrecht approved these changes
Different breed 😤

2021-02-17 18:25 UTC, merged