Item search
carteralbrecht/bitewise pull request #39
Opened 2021-03-28 21:06 UTC by bkingsley727

Item Search
Scroll to Menu Item in restaurant
Fixed missing info on Restaurant Header
Added Open in Maps

2021-03-29 23:08 UTC, carteralbrecht requested changes
I think we can make it faster

2021-03-29 23:08 UTC, carteralbrecht commented on lib/pages/homePage.dart
> +
Could we only do the work for whatever tab the user is currently on? Doing both up front is very expensive

2021-03-29 23:08 UTC, carteralbrecht commented on lib/pages/homePage.dart
> +      var dist = await GeoUtil.distanceToRestaurant(currentLocation, r);
If we had a GeoUtil.distanceToMenuItem, could we avoid making the `await Documenu.getRestaurant()` call right now? What fields of `r` are actually needed at this time?

2021-03-29 23:17 UTC, carteralbrecht commented on lib/components/menuItemSearchTile.dart
> +                child: Text(" • " + widget.milesAway.toStringAsFixed(2))
<img width="318" alt="Screen Shot 2021-03-29 at 7 16 46 PM" src="https://user-images.githubusercontent.com/50386308/112911399-57bda180-90c3-11eb-8654-b55e8c27b14b.png">

Should this say miles away? or have a unit of some sort

2021-03-30 13:22 UTC, bkingsley727 commented on lib/pages/homePage.dart
> +      var dist = await GeoUtil.distanceToRestaurant(currentLocation, r);
We need all of r in order to build the route for the restaurant page for the onTap() method. I can redesign the card if we don't wat some of the other info but I believe there is o way to combine any of the calls currently

2021-03-31 01:38 UTC, carteralbrecht approved these changes

2021-03-31 01:38 UTC, merged